name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          timeout: 1m            # SSH bağlanma süresi
          command_timeout: 40m   # Komutlar uzun sürerse zaman aşımı olmasın
          debug: true
          script: |
            set -euo pipefail

            # ---- Ayarlar ----
            APP_PATH="${{ secrets.EC2_PATH }}"
            if [ -z "${APP_PATH:-}" ]; then APP_PATH="/var/www/bilginotu"; fi

            # ---- İlk kurulum / Güncelleme ----
            if [ ! -d "$APP_PATH/.git" ]; then
              sudo rm -rf "$APP_PATH"
              mkdir -p "$APP_PATH"
              git clone https://github.com/eminoglucagri/AdliYardimSistemi.git "$APP_PATH"
            fi

            cd "$APP_PATH"
            git fetch --all
            git checkout main
            git pull --ff-only origin main

            # ---- Node & PM2 ----
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm i -g pm2
            fi

            # ---- Bağımlılıklar + Build ----
            export CI=true
            npm ci --no-audit --no-fund || npm install --no-audit --no-fund
            npm run build --if-present

            # ---- bootstrap.cjs (doğru .env yolu ile) ----
            printf "require('dotenv').config({ path: '%s/.env' });\n(async () => { await import('./dist/index.js'); })();\n" "$APP_PATH" > bootstrap.cjs

            # ---- PM2 restart ----
            pm2 describe bilginotu >/dev/null 2>&1 && pm2 restart bilginotu --update-env || pm2 start "$APP_PATH/bootstrap.cjs" --name bilginotu --cwd "$APP_PATH"
            pm2 save

            # ---- Nginx test ----
            sudo nginx -t && sudo systemctl reload nginx
