name: Deploy to EC2 (/bilginotu)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -e

            APP_PATH=${{ secrets.EC2_PATH }}
            if [ -z "$APP_PATH" ]; then APP_PATH=/var/www/bilginotu; fi

            # İlk kurulum / güncelleme
            if [ ! -d "$APP_PATH/.git" ]; then
              sudo rm -rf "$APP_PATH"
              mkdir -p "$APP_PATH"
              git clone https://github.com/eminoglucagri/AdliYardimSistemi.git "$APP_PATH"
            fi

            cd "$APP_PATH"
            git fetch --all
            git checkout main
            git pull origin main

            # Node 22 ve PM2 (yüklü değilse yükle)
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm i -g pm2
            fi

            npm ci || npm install
            npm run build --if-present

            # bootstrap.cjs (dotenv + ESM import)
            if [ ! -f bootstrap.cjs ]; then
              cat > bootstrap.cjs <<'EOF'
require('dotenv').config({ path: '/var/www/bilginotu/.env' });
(async () => { await import('./dist/index.js'); })();
EOF
            fi

            pm2 delete bilginotu || true
            pm2 start "$APP_PATH/bootstrap.cjs" --name bilginotu --cwd "$APP_PATH"
            pm2 save
