script: |
  set -e
  APP_PATH=${{ secrets.EC2_PATH }}
  if [ -z "$APP_PATH" ]; then APP_PATH=/var/www/bilginotu; fi

  # İlk kurulum / güncelleme
  if [ ! -d "$APP_PATH/.git" ]; then
    rm -rf "$APP_PATH"
    mkdir -p "$APP_PATH"
    git clone https://github.com/eminoglucagri/AdliYardimSistemi.git "$APP_PATH"
  fi
  cd "$APP_PATH"
  git fetch --all
  git checkout main
  git pull origin main

  # Node & PM2 (gerekirse)
  command -v node || (curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs)
  command -v pm2 || sudo npm i -g pm2

  npm ci || npm install
  npm run build --if-present

  # bootstrap.cjs yoksa oluştur (dotenv + ESM import)
  if [ ! -f bootstrap.cjs ]; then
    cat > bootstrap.cjs <<'EOF'
require('dotenv').config({ path: '/var/www/bilginotu/.env' });
(async () => { await import('./dist/index.js'); })();
EOF
  fi

  # Çalıştır / güncelle
  pm2 delete bilginotu || true
  pm2 start "$APP_PATH/bootstrap.cjs" --name bilginotu --cwd "$APP_PATH"
  pm2 save
